name: Frontend CICD

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Install AWS CLI
        uses: aws-actions/aws-cli@v2
    
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
    
      - name: Install Node.js dependencies
        run: npm ci
    
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws configure
    
      - name: Add execute permission to the script
        run: chmod +x uploadDataToDynamoDB.sh
    
      - name: Run custom script
        run: sh uploadDataToDynamoDB.sh
    
      - name: Get API Gateway endpoint
        run: |
          API_ID=$(aws cloudformation describe-stacks --stack-name beatoncloud-stack --query "Stacks[0].Outputs[?OutputKey=='APIEndpoint'].OutputValue" --output text)
          echo "{\"ApiUrl\": \"$API_ID\"}" > src/config.json
    
      - name: Build project
        run: npm run build
        env: 
          CI: ""