name: Frontend CICD

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
    
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
    
      - name: Install Node.js dependencies
        run: npm ci
    
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws configure
    
      - name: Add execute permission to the script
        run: chmod +x uploadDataToDynamoDB.sh
    
      - name: Run custom script
        run: sh uploadDataToDynamoDB.sh
    
      - name: Get API Gateway endpoint
        run: |
          API_ID=$(aws cloudformation describe-stacks --stack-name beatoncloud-stack --query "Stacks[0].Outputs[?OutputKey=='APIEndpoint'].OutputValue" --output text)
          echo "{\"ApiUrl\": \"$API_ID\"}" > src/config.json
    
      - name: Build project
        run: npm run build
        env: 
          CI: ""
    
      - name: Get S3 Bucket URL
        run: |
          S3_BUCKET_URL=$(aws cloudformation describe-stacks --stack-name beatoncloud-stack --query "Stacks[0].Outputs[?OutputKey=='DeploytoCloudFront'].OutputValue" --output text)
          echo "$S3_BUCKET_URL" > s3sync.sh
          sed -i 's/environment\/personalizeworkshop/work\/BeatOnCloud-Personalize\/BeatOnCloud-Personalize/g' s3sync.sh
    
      - name: Deploy to S3
        run: sh s3sync.sh